---
- name: Download Windows updates
  hosts: windows_manual_patching
  tasks:
  - name: Search, download and install Windows updates
    throttle: 1
    ansible.windows.win_updates:
      server_selection: "windows_update"
      category_names: '*'
      state: installed
      reboot: true
      log_path: C:\temp\ansible_wu.txt
    register: update_results
