# windows_servers:
#   hosts: 

windows_manual_patching:
  hosts:
    HOST.ad.domain.local:

windows_tierzero_servers:
  hosts:
    DC.ad.domain.local:

windows_admin_server:
  hosts:
    ADMIN.ad.domain.local:

all_windows:
  children:
    windows_manual_patching:
    windows_admin_server:
    windows_tierzero_servers:
  vars:
    ansible_connection: winrm
    ansible_winrm_transport: kerberos
    ansible_user: "{{ activedirectory_username }}"
    ansible_password: "{{ activedirectory_password }}"
    ansible_winrm_server_cert_validation: ignore
    ansible_port: 5985
    ansible_winrm_kerberos_delegation: true
